### ISSUE TITLE
IOS App

### ISSUE THREAD

**Issue by brysonchaseadmin** [swingmx/android#60]
When will there be an IOS App?

**Comment by Ericgacoki** [comment]
Hi @brysonchaseadmin,

Thank you for reaching out! We currently don’t have plans for an iOS app, but rest assured, any updates will be shared as soon as that changes.

**Comment by Ericgacoki** [comment]
closing this for now

**Comment by brysonchaseadmin** [comment]
> Hi @brysonchaseadmin,
> 
> Thank you for reaching out! We currently don’t have plans for an iOS app, but rest assured, any updates will be shared as soon as that changes.

If your not gonna make an IOS app, could you at least make the website a bit more mobile friendly?
